version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: confighub-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ConfigHubDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: confighub-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # Uygulama bağlantı portu
      - "15672:15672" # Tarayıcı Yönetim Ekranı portu
    restart: unless-stopped

  config_api:
    build:
      context: .
      dockerfile: DistributedConfigHub.Api/Dockerfile
    container_name: confighub-api
    ports:
      - "5173:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=ConfigHubDb;Username=postgres;Password=postgres
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      - postgres
      - rabbitmq
    restart: unless-stopped

  demo_consumer:
    build:
      context: .
      dockerfile: DemoConsumerApp/Dockerfile
    container_name: confighub-demo
    environment:
      - DistributedConfig__ApiBaseUrl=http://config_api:8080
      - DistributedConfig__RabbitMqHostName=rabbitmq
    depends_on:
      - config_api
      - rabbitmq
    restart: unless-stopped

volumes:
  postgres_data:
