services:
  postgres:
    image: postgres:15-alpine
    container_name: confighub-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ConfigHubDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: confighub-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # Uygulama bağlantı portu
      - "15672:15672" # Tarayıcı Yönetim Ekranı portu
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  config_api:
    build:
      context: .
      dockerfile: DistributedConfigHub.Api/Dockerfile
    container_name: confighub-api
    ports:
      - "5173:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=ConfigHubDb;Username=postgres;Password=postgres
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  demo_consumer:
    build:
      context: .
      dockerfile: DemoConsumerApp/Dockerfile
    container_name: confighub-demo
    ports:
      - "5174:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production # Can be configured for Development, Staging and Production.
      - DistributedConfig__ApiBaseUrl=http://config_api:8080
      - DistributedConfig__RabbitMqHostName=rabbitmq
    depends_on:
      config_api:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
