// <auto-generated />
using System;
using DistributedConfigHub.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DistributedConfigHub.Infrastructure.Migrations
{
    [DbContext(typeof(ConfigDbContext))]
    [Migration("20260407201002_UpdateIbbSeedData")]
    partial class UpdateIbbSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DistributedConfigHub.Domain.Entities.ConfigurationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name", "ApplicationName", "Environment")
                        .IsUnique();

                    b.ToTable("Configurations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            ApplicationName = "SERVICE-A",
                            Environment = "dev",
                            IsActive = true,
                            Name = "PaymentGatewayUrl",
                            Type = "String",
                            Value = "https://dev-odeme.ibb.istanbul"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            ApplicationName = "SERVICE-A",
                            Environment = "dev",
                            IsActive = true,
                            Name = "MaxIstanbulKartTransactionsPerMin",
                            Type = "Int",
                            Value = "100"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            ApplicationName = "SERVICE-A",
                            Environment = "dev",
                            IsActive = true,
                            Name = "IsMaintenanceModeEnabled",
                            Type = "Boolean",
                            Value = "true"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            ApplicationName = "SERVICE-A",
                            Environment = "staging",
                            IsActive = true,
                            Name = "PaymentGatewayUrl",
                            Type = "String",
                            Value = "https://test-odeme.ibb.istanbul"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            ApplicationName = "SERVICE-A",
                            Environment = "staging",
                            IsActive = true,
                            Name = "MaxIstanbulKartTransactionsPerMin",
                            Type = "Int",
                            Value = "1000"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            ApplicationName = "SERVICE-A",
                            Environment = "staging",
                            IsActive = true,
                            Name = "IsMaintenanceModeEnabled",
                            Type = "Boolean",
                            Value = "false"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            ApplicationName = "SERVICE-A",
                            Environment = "prod",
                            IsActive = true,
                            Name = "PaymentGatewayUrl",
                            Type = "String",
                            Value = "https://odeme.ibb.istanbul"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            ApplicationName = "SERVICE-A",
                            Environment = "prod",
                            IsActive = true,
                            Name = "MaxIstanbulKartTransactionsPerMin",
                            Type = "Int",
                            Value = "50000"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            ApplicationName = "SERVICE-A",
                            Environment = "prod",
                            IsActive = true,
                            Name = "IsMaintenanceModeEnabled",
                            Type = "Boolean",
                            Value = "false"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
